### ISSUE TITLE
Missing module asg. 

### ISSUE THREAD

**Issue by baardl** [itsdalmo/tf-modules#25]
Hi @itsdalmo 
When I try to use your script for building an Cluster with task definitions I get the error below.

```bash
> terraform get
Get: git::https://github.com/itsdalmo/tf-modules.git//ec2/alb
Get: git::https://github.com/itsdalmo/tf-modules.git//container/cluster
Get: git::https://github.com/itsdalmo/tf-modules.git//container/service
Error loading modules: module asg: invalid source string: ../../ec2/asg
```

**Comment by itsdalmo** [comment]
This is a bug in terraform 0.10.6 (latest version):
https://github.com/hashicorp/terraform/issues/16138

I'm using terraform 0.10.5 while waiting for the fix to be released, which should be any day now given the 2-ish week release cycle of terraform :)
